/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-06-09 16:41:44 UTC)
 * on 2014-06-23 at 12:12:34 UTC 
 * Modify at your own risk.
 */

package placer.backend.searchobjectendpoint;

/**
 * Service definition for Searchobjectendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link SearchobjectendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Searchobjectendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the searchobjectendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://placer-siftech.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "searchobjectendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Searchobjectendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Searchobjectendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "dbTest".
   *
   * This request holds the parameters needed by the the searchobjectendpoint server.  After setting
   * any optional parameters, call the {@link DbTest#execute()} method to invoke the remote operation.
   *
   * @param gid
   * @return the request
   */
  public DbTest dbTest(java.lang.Integer gid) throws java.io.IOException {
    DbTest result = new DbTest(gid);
    initialize(result);
    return result;
  }

  public class DbTest extends SearchobjectendpointRequest<placer.backend.searchobjectendpoint.model.ResultObject> {

    private static final String REST_PATH = "dbTest/{gid}";

    /**
     * Create a request for the method "dbTest".
     *
     * This request holds the parameters needed by the the searchobjectendpoint server.  After setting
     * any optional parameters, call the {@link DbTest#execute()} method to invoke the remote
     * operation. <p> {@link
     * DbTest#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param gid
     * @since 1.13
     */
    protected DbTest(java.lang.Integer gid) {
      super(Searchobjectendpoint.this, "POST", REST_PATH, null, placer.backend.searchobjectendpoint.model.ResultObject.class);
      this.gid = com.google.api.client.util.Preconditions.checkNotNull(gid, "Required parameter gid must be specified.");
    }

    @Override
    public DbTest setAlt(java.lang.String alt) {
      return (DbTest) super.setAlt(alt);
    }

    @Override
    public DbTest setFields(java.lang.String fields) {
      return (DbTest) super.setFields(fields);
    }

    @Override
    public DbTest setKey(java.lang.String key) {
      return (DbTest) super.setKey(key);
    }

    @Override
    public DbTest setOauthToken(java.lang.String oauthToken) {
      return (DbTest) super.setOauthToken(oauthToken);
    }

    @Override
    public DbTest setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (DbTest) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public DbTest setQuotaUser(java.lang.String quotaUser) {
      return (DbTest) super.setQuotaUser(quotaUser);
    }

    @Override
    public DbTest setUserIp(java.lang.String userIp) {
      return (DbTest) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Integer gid;

    /**

     */
    public java.lang.Integer getGid() {
      return gid;
    }

    public DbTest setGid(java.lang.Integer gid) {
      this.gid = gid;
      return this;
    }

    @Override
    public DbTest set(String parameterName, Object value) {
      return (DbTest) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getSearchObject".
   *
   * This request holds the parameters needed by the the searchobjectendpoint server.  After setting
   * any optional parameters, call the {@link GetSearchObject#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetSearchObject getSearchObject(java.lang.String id) throws java.io.IOException {
    GetSearchObject result = new GetSearchObject(id);
    initialize(result);
    return result;
  }

  public class GetSearchObject extends SearchobjectendpointRequest<placer.backend.searchobjectendpoint.model.SearchObject> {

    private static final String REST_PATH = "searchobject/{id}";

    /**
     * Create a request for the method "getSearchObject".
     *
     * This request holds the parameters needed by the the searchobjectendpoint server.  After setting
     * any optional parameters, call the {@link GetSearchObject#execute()} method to invoke the remote
     * operation. <p> {@link GetSearchObject#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetSearchObject(java.lang.String id) {
      super(Searchobjectendpoint.this, "GET", REST_PATH, null, placer.backend.searchobjectendpoint.model.SearchObject.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetSearchObject setAlt(java.lang.String alt) {
      return (GetSearchObject) super.setAlt(alt);
    }

    @Override
    public GetSearchObject setFields(java.lang.String fields) {
      return (GetSearchObject) super.setFields(fields);
    }

    @Override
    public GetSearchObject setKey(java.lang.String key) {
      return (GetSearchObject) super.setKey(key);
    }

    @Override
    public GetSearchObject setOauthToken(java.lang.String oauthToken) {
      return (GetSearchObject) super.setOauthToken(oauthToken);
    }

    @Override
    public GetSearchObject setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetSearchObject) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetSearchObject setQuotaUser(java.lang.String quotaUser) {
      return (GetSearchObject) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetSearchObject setUserIp(java.lang.String userIp) {
      return (GetSearchObject) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetSearchObject setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetSearchObject set(String parameterName, Object value) {
      return (GetSearchObject) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertSearchObject".
   *
   * This request holds the parameters needed by the the searchobjectendpoint server.  After setting
   * any optional parameters, call the {@link InsertSearchObject#execute()} method to invoke the
   * remote operation.
   *
   * @param content the {@link placer.backend.searchobjectendpoint.model.SearchObject}
   * @return the request
   */
  public InsertSearchObject insertSearchObject(placer.backend.searchobjectendpoint.model.SearchObject content) throws java.io.IOException {
    InsertSearchObject result = new InsertSearchObject(content);
    initialize(result);
    return result;
  }

  public class InsertSearchObject extends SearchobjectendpointRequest<placer.backend.searchobjectendpoint.model.SearchObject> {

    private static final String REST_PATH = "searchobject";

    /**
     * Create a request for the method "insertSearchObject".
     *
     * This request holds the parameters needed by the the searchobjectendpoint server.  After setting
     * any optional parameters, call the {@link InsertSearchObject#execute()} method to invoke the
     * remote operation. <p> {@link InsertSearchObject#initialize(com.google.api.client.googleapis.ser
     * vices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param content the {@link placer.backend.searchobjectendpoint.model.SearchObject}
     * @since 1.13
     */
    protected InsertSearchObject(placer.backend.searchobjectendpoint.model.SearchObject content) {
      super(Searchobjectendpoint.this, "POST", REST_PATH, content, placer.backend.searchobjectendpoint.model.SearchObject.class);
    }

    @Override
    public InsertSearchObject setAlt(java.lang.String alt) {
      return (InsertSearchObject) super.setAlt(alt);
    }

    @Override
    public InsertSearchObject setFields(java.lang.String fields) {
      return (InsertSearchObject) super.setFields(fields);
    }

    @Override
    public InsertSearchObject setKey(java.lang.String key) {
      return (InsertSearchObject) super.setKey(key);
    }

    @Override
    public InsertSearchObject setOauthToken(java.lang.String oauthToken) {
      return (InsertSearchObject) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertSearchObject setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertSearchObject) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertSearchObject setQuotaUser(java.lang.String quotaUser) {
      return (InsertSearchObject) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertSearchObject setUserIp(java.lang.String userIp) {
      return (InsertSearchObject) super.setUserIp(userIp);
    }

    @Override
    public InsertSearchObject set(String parameterName, Object value) {
      return (InsertSearchObject) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listSearchObject".
   *
   * This request holds the parameters needed by the the searchobjectendpoint server.  After setting
   * any optional parameters, call the {@link ListSearchObject#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListSearchObject listSearchObject() throws java.io.IOException {
    ListSearchObject result = new ListSearchObject();
    initialize(result);
    return result;
  }

  public class ListSearchObject extends SearchobjectendpointRequest<placer.backend.searchobjectendpoint.model.CollectionResponseSearchObject> {

    private static final String REST_PATH = "searchobject";

    /**
     * Create a request for the method "listSearchObject".
     *
     * This request holds the parameters needed by the the searchobjectendpoint server.  After setting
     * any optional parameters, call the {@link ListSearchObject#execute()} method to invoke the
     * remote operation. <p> {@link ListSearchObject#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListSearchObject() {
      super(Searchobjectendpoint.this, "GET", REST_PATH, null, placer.backend.searchobjectendpoint.model.CollectionResponseSearchObject.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListSearchObject setAlt(java.lang.String alt) {
      return (ListSearchObject) super.setAlt(alt);
    }

    @Override
    public ListSearchObject setFields(java.lang.String fields) {
      return (ListSearchObject) super.setFields(fields);
    }

    @Override
    public ListSearchObject setKey(java.lang.String key) {
      return (ListSearchObject) super.setKey(key);
    }

    @Override
    public ListSearchObject setOauthToken(java.lang.String oauthToken) {
      return (ListSearchObject) super.setOauthToken(oauthToken);
    }

    @Override
    public ListSearchObject setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListSearchObject) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListSearchObject setQuotaUser(java.lang.String quotaUser) {
      return (ListSearchObject) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListSearchObject setUserIp(java.lang.String userIp) {
      return (ListSearchObject) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListSearchObject setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListSearchObject setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListSearchObject set(String parameterName, Object value) {
      return (ListSearchObject) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeSearchObject".
   *
   * This request holds the parameters needed by the the searchobjectendpoint server.  After setting
   * any optional parameters, call the {@link RemoveSearchObject#execute()} method to invoke the
   * remote operation.
   *
   * @param id
   * @return the request
   */
  public RemoveSearchObject removeSearchObject(java.lang.String id) throws java.io.IOException {
    RemoveSearchObject result = new RemoveSearchObject(id);
    initialize(result);
    return result;
  }

  public class RemoveSearchObject extends SearchobjectendpointRequest<Void> {

    private static final String REST_PATH = "searchobject/{id}";

    /**
     * Create a request for the method "removeSearchObject".
     *
     * This request holds the parameters needed by the the searchobjectendpoint server.  After setting
     * any optional parameters, call the {@link RemoveSearchObject#execute()} method to invoke the
     * remote operation. <p> {@link RemoveSearchObject#initialize(com.google.api.client.googleapis.ser
     * vices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveSearchObject(java.lang.String id) {
      super(Searchobjectendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveSearchObject setAlt(java.lang.String alt) {
      return (RemoveSearchObject) super.setAlt(alt);
    }

    @Override
    public RemoveSearchObject setFields(java.lang.String fields) {
      return (RemoveSearchObject) super.setFields(fields);
    }

    @Override
    public RemoveSearchObject setKey(java.lang.String key) {
      return (RemoveSearchObject) super.setKey(key);
    }

    @Override
    public RemoveSearchObject setOauthToken(java.lang.String oauthToken) {
      return (RemoveSearchObject) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveSearchObject setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveSearchObject) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveSearchObject setQuotaUser(java.lang.String quotaUser) {
      return (RemoveSearchObject) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveSearchObject setUserIp(java.lang.String userIp) {
      return (RemoveSearchObject) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemoveSearchObject setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveSearchObject set(String parameterName, Object value) {
      return (RemoveSearchObject) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateSearchObject".
   *
   * This request holds the parameters needed by the the searchobjectendpoint server.  After setting
   * any optional parameters, call the {@link UpdateSearchObject#execute()} method to invoke the
   * remote operation.
   *
   * @param content the {@link placer.backend.searchobjectendpoint.model.SearchObject}
   * @return the request
   */
  public UpdateSearchObject updateSearchObject(placer.backend.searchobjectendpoint.model.SearchObject content) throws java.io.IOException {
    UpdateSearchObject result = new UpdateSearchObject(content);
    initialize(result);
    return result;
  }

  public class UpdateSearchObject extends SearchobjectendpointRequest<placer.backend.searchobjectendpoint.model.SearchObject> {

    private static final String REST_PATH = "searchobject";

    /**
     * Create a request for the method "updateSearchObject".
     *
     * This request holds the parameters needed by the the searchobjectendpoint server.  After setting
     * any optional parameters, call the {@link UpdateSearchObject#execute()} method to invoke the
     * remote operation. <p> {@link UpdateSearchObject#initialize(com.google.api.client.googleapis.ser
     * vices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param content the {@link placer.backend.searchobjectendpoint.model.SearchObject}
     * @since 1.13
     */
    protected UpdateSearchObject(placer.backend.searchobjectendpoint.model.SearchObject content) {
      super(Searchobjectendpoint.this, "PUT", REST_PATH, content, placer.backend.searchobjectendpoint.model.SearchObject.class);
    }

    @Override
    public UpdateSearchObject setAlt(java.lang.String alt) {
      return (UpdateSearchObject) super.setAlt(alt);
    }

    @Override
    public UpdateSearchObject setFields(java.lang.String fields) {
      return (UpdateSearchObject) super.setFields(fields);
    }

    @Override
    public UpdateSearchObject setKey(java.lang.String key) {
      return (UpdateSearchObject) super.setKey(key);
    }

    @Override
    public UpdateSearchObject setOauthToken(java.lang.String oauthToken) {
      return (UpdateSearchObject) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateSearchObject setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateSearchObject) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateSearchObject setQuotaUser(java.lang.String quotaUser) {
      return (UpdateSearchObject) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateSearchObject setUserIp(java.lang.String userIp) {
      return (UpdateSearchObject) super.setUserIp(userIp);
    }

    @Override
    public UpdateSearchObject set(String parameterName, Object value) {
      return (UpdateSearchObject) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Searchobjectendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Searchobjectendpoint}. */
    @Override
    public Searchobjectendpoint build() {
      return new Searchobjectendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link SearchobjectendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setSearchobjectendpointRequestInitializer(
        SearchobjectendpointRequestInitializer searchobjectendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(searchobjectendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
